Instance: ""

# Site information that should match the CE Topology registration
Topology:
  Resource: RESOURCE_NAME
  ResourceGroup: RESOURCE_GROUP
  Sponsor: osg:100
  Contact: RESOURCE_CONTACT
  ContactEmail: support@example.edu
  City: City
  Country: US
  Latitude: 0.00
  Longitude: 0.00

RemoteCluster:
  # SSH host
  LoginHost: remote-ssh.login.org
  PrivateKeySecret: lincolnb-bosco # maps to SLATE secret
  # condor, slurm, pbs, sge, or lsf
  Batch: slurm
  Memory: 1024
  CoresPerNode: 4
  MaxWallTime: 1440
  # Absolute path to the local WN client installation
  # Do not use environment variables!
  GridDir: /home/osguser/bosco-osg-wn-client
  # Worker node scratch space for payload jobs
  # Do not use environment variables!
  WorkerNodeTemp: /tmp
  # <FQDN>:<PORT> for the site's local squid server
  Squid: null

Networking:
  # The hostname that the CE should use. 
  # Appropriate A and PTR DNS records must exist.
  Hostname: ""
  # The preferred IP address which should be requested from the LoadBalancer. 
  # This may be left as null to express no preference. 
  # Setting this may be useful when redeploying a CE in order to try to get
  # back the same IP address that was used previously. 
  RequestIP: null

# VOMS FQAN to remote user mapping
# This list controls the VOs accepted by the CE and the users they are
# mapped to on the remote site.
#
# To disallow VOs, remove the relevant item from the list.
# To change the remote user for a given VO, change the value (e.g. osg01)
# To add custom VOMS FQAN mappings, add a new item to the list.
# VOMS FQANs can include "*" wildcards.
VoRemoteUserMapping:
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/OSG.yaml
  - "/osg/Role=NULL/Capability=NULL": osg01
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/GLOW.yaml
  - "/GLOW/Role=htpc/Capability=NULL": osg02
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/HCC.yaml
  - "/hcc/Role=NULL/Capability=NULL": osg03
  # CMS
  - "/cms/*": osg04
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/Fermilab.yaml
  - "/fermilab/*": osg05
  # osg06 reserved for JLAB
  # LIGO-Virgo collaboration
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/LIGO.yaml
  - "/osg/ligo/Role=NULL/Capability=NULL": osg07
  - "/virgo/ligo/Role=NULL/Capability=NULL": osg07
  # Brookhaven National Lab VOs
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/sPHENIX.yaml
  - "/sdcc/Role=NULL/Capability=NULL": osg08
  - "/sphenix/Role=NULL/Capability=NULL": osg08
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/ATLAS.yaml
  - "/atlas/*": osg09
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/Gluex.yaml
  - "/Gluex/Role=NULL/Capability=NULL": osg10
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/DUNE.yaml
  - "/dune/Role=pilot/Capability=NULL": osg11
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/IceCube.yaml
  - "/icecube/Role=pilot/Capability=NULL": osg12
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/XENON.yaml
  - "/xenon.biggrid.nl/Role=NULL/Capability=NULL": osg13

# DN to remote user mapping
# For example, you may add your personal certificate's subject DN so
# that you can submit jobs to this CE
#DnRemoteUserMapping:
#  - "/DC=foo/DC=bar/OU=Organic Units/OU=Users/CN=YourUserName": osg01

# Specify additional HTCondor-CE configuration
# HTCondorCeConfig: |+

# Options to allow override of the bosco directory from arbitrary git repos
# Bosco override dirs are expected in the following location in the git repo:
#   <RESOURCE NAME>/bosco_override/
BoscoOverrides:
  Enabled: false
  GitEndpoint: https://github.com/slateci/bosco-override-template
  GitKeySecret: null

# Enable a logging sidecar
HTTPLogger:
  Enabled: true
  # If you want to insert a password instead of using a randomly generated one,
  # point Secret to a K8S/SLATE secret below.
  # Secret: my-secret

# Use a pre-existing certificate/key pair stored in a secret with
# 'hostcert.pem' and 'hostkey.pem' keys for the host certificate and
# key, respectively
Certificate:
  Secret: null

# FOR DEVELOPMENT PURPOSES ONLY!
# Setting 'Enabled: true' below does the following:
# - Configures the CE as an ITB host
# - Generates a test CA and self-signed host cert/key pair
Developer:
  Enabled: false
